import { Artifact } from "../interfaces/artifact.interface";

export const artifactList: Artifact[] = [
    { name: 'Battery', source: './assets/icons/battery.png' },
    { name: 'Broken Rock', source: './assets/icons/broken-rock.png' },
    { name: 'Bubble', source: './assets/icons/bubble.png' },
    { name: 'Cavity', source: './assets/icons/cavity.png' },
    { name: 'Chocolate Bar', source: './assets/icons/chocolate-bar.png' },
    { name: 'Cilliate', source: './assets/icons/cilliate.png' },
    { name: 'Compass', source: './assets/icons/compass.png' },
    { name: 'Crest', source: './assets/icons/crest.png' },
    { name: 'Crown', source: './assets/icons/crown.png' },
    { name: 'Crust', source: './assets/icons/crust.png' },
    { name: 'Crystal Thorn', source: './assets/icons/crystal-thorn.png' },
    { name: 'Crystal', source: './assets/icons/crystal.png' },
    { name: 'Dead Sponge', source: './assets/icons/dead-sponge.png' },
    { name: 'Devil\'s Mushroom', source: './assets/icons/devils-mushroom.png' },
    { name: 'Droplets', source: './assets/icons/droplets.png' },
    { name: 'Eye', source: './assets/icons/eye.png' },
    { name: 'Flash', source: './assets/icons/flash.png' },
    { name: 'Fireball', source: './assets/icons/fireball.png' },
    { name: 'Flaw', source: './assets/icons/flaw.png' },
    { name: 'Flower Bud', source: './assets/icons/flower-bud.png' },
    { name: 'Flytrap', source: './assets/icons/flytrap.png' },
    { name: 'Glare', source: './assets/icons/glare.png' },
    { name: 'Goldfish', source: './assets/icons/goldfish.png' },
    { name: 'Gravi', source: './assets/icons/gravi.png' },
    { name: 'Harp', source: './assets/icons/harp.png' },
    { name: 'Horn', source: './assets/icons/horn.png' },
    { name: 'Hypercube', source: './assets/icons/hypercube.png' },
    { name: 'Jellyfish', source: './assets/icons/jellyfish.png' },
    { name: 'Kolobok', source: './assets/icons/kolobok.png' },
    { name: 'Lantern', source: './assets/icons/lantern.png' },
    { name: 'Liquid Rock', source: './assets/icons/liquid-rock.png' },
    { name: 'Lyre', source: './assets/icons/lyre.png' },
    { name: 'Magic Cube', source: './assets/icons/magic-cube.png' },
    { name: 'Magma', source: './assets/icons/magma.png' },
    { name: 'Mama\'s Beads', source: './assets/icons/mamas-beads.png' },
    { name: 'Meat Chunk', source: './assets/icons/meat-chunk.png' },
    { name: 'Meat Lighter', source: './assets/icons/meat-lighter.png' },
    { name: 'Mica', source: './assets/icons/mica.png' },
    { name: 'Mold', source: './assets/icons/mold.png' },
    { name: 'Moonlight', source: './assets/icons/moonlight.png' },
    { name: 'Night Star', source: './assets/icons/night-star.png' },
    { name: 'Pebble', source: './assets/icons/pebble.png' },
    { name: 'Pellicle', source: './assets/icons/pellicle.png' },
    { name: 'Petal', source: './assets/icons/petal.png' },
    { name: 'Plasma', source: './assets/icons/plasma.png' },
    { name: 'Rat King', source: './assets/icons/rat-king.png' },
    { name: 'Rosin', source: './assets/icons/rosin.png' },
    { name: 'Sapphire', source: './assets/icons/sapphire.png' },
    { name: 'Shell', source: './assets/icons/shell.png' },
    { name: 'Shop Class', source: './assets/icons/shop-class.png' },
    { name: 'Skipjack', source: './assets/icons/skipjack.png' },
    { name: 'Slime', source: './assets/icons/slime.png' },
    { name: 'Slug', source: './assets/icons/slug.png' },
    { name: 'Snowflake', source: './assets/icons/snowflake.png' },
    { name: 'Soul', source: './assets/icons/soul.png' },
    { name: 'Sparkler', source: './assets/icons/sparkler.png' },
    { name: 'Spinner', source: './assets/icons/spinner.png' },
    { name: 'Spring', source: './assets/icons/spring.png' },
    { name: 'Starfish', source: './assets/icons/starfish.png' },
    { name: 'Steak', source: './assets/icons/steak.png' },
    { name: 'Stone Blood', source: './assets/icons/stone-blood.png' },
    { name: 'Stone Heart', source: './assets/icons/stone-heart.png' },
    { name: 'Thorn', source: './assets/icons/thorn.png' },
    { name: 'Thunderberry', source: './assets/icons/thunderberry.png' },
    { name: 'Torch', source: './assets/icons/torch.png' },
    { name: 'Tourist Breakfast', source: './assets/icons/tourist-breakfast.png' },
    { name: 'Urchin', source: './assets/icons/urchin.png' },
    { name: 'Whirlwind', source: './assets/icons/whirlwind.png' },
    { name: 'Wierd Ball', source: './assets/icons/wierd-ball.png' },
    { name: 'Wierd Bolt', source: './assets/icons/wierd-bolt.png' },
    { name: 'Wierd Flower', source: './assets/icons/wierd-flower.png' },
    { name: 'Wierd Nut', source: './assets/icons/wierd-nut.png' },
    { name: 'Wierd Pot', source: './assets/icons/wierd-pot.png' },
    { name: 'Wierd Water', source: './assets/icons/wierd-water.png' },
    { name: 'Wrenched', source: './assets/icons/wrenched.png' }
]